### ISSUE TITLE
The problem I have met

### ISSUE THREAD

**Issue by guardstrikeo** [guardstrikelab/carla_apollo_bridge#25]
### Discussed in https://github.com/orgs/guardstrikelab/discussions/24

<div type='discussions-op-text'>

<sup>Originally posted by **Leason-ly** November 21, 2022</sup>
Hello, I've followed your guide to setup. However, there was a problem at the and of the bridge. When I run the 
file called "carla_cyber_bridge/bridge.py", I'm confronted with an error.

I1121 07:44:25.121304  7055 global_data.cc:119] [cyber_py] host ip: 172.17.0.2
[2022-11-21 07:44:25,123] [carla_bridge] [INFO]: The config file path is carla_cyber_bridge/config/settings.yaml.
[2022-11-21 07:44:25,125] [carla_bridge] [INFO]: Trying to connect to 172.17.0.2:2000
[2022-11-21 07:44:55,128] [carla_bridge] [ERROR]: Error: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.2:2000
Traceback (most recent call last):
  File "carla_cyber_bridge/bridge.py", line 487, in <module>
    main()
  File "carla_cyber_bridge/bridge.py", line 473, in main
    carla_world = carla_client.get_world()
RuntimeError: time-out of 30000ms while waiting for the simulator, make sure the simulator is ready and connected to 172.17.0.2:2000

I wish you can help me solve the problem, th-x!
</div>

**Comment by 2019211753** [comment]
I meet this error too. How did you solve this? Thanks a lot!
